-- 001_baseline.sql
--
-- Esquema de partida: las tablas que hoy viven en Supabase (§2.2), reconstruidas
-- a partir de cómo las usa el código.
--
-- Es idempotente a propósito. Hay dos caminos y los dos terminan igual:
--   1. Corte real: se restaura el pg_dump de Supabase (scripts/supabase-export.sh)
--      y después corre esta migración. Como las tablas ya existen, no hace nada
--      salvo añadir los índices que falten. Manda el volcado.
--   2. Base nueva (pruebas, desarrollo): crea el esquema desde cero.
--
-- Si el volcado de Supabase trae columnas que aquí no aparecen, se conservan tal
-- cual; ninguna migración borra columnas.

create sequence if not exists customers_code_seq;

create table if not exists customers (
  id            bigint generated by default as identity primary key,
  customer_code text        default ('CLI-' || lpad(nextval('customers_code_seq')::text, 6, '0')),
  display_name  text,
  legal_name    text,
  notes         text,
  status        text        not null default 'active',
  first_seen_at timestamptz not null default now(),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists customer_contacts (
  id               bigint generated by default as identity primary key,
  customer_id      bigint      references customers(id) on delete cascade,
  contact_type     text        not null,             -- whatsapp | email | telegram | otro
  contact_value    text        not null,
  normalized_value text,
  is_primary       boolean     not null default false,
  is_verified      boolean     not null default false,
  status           text        not null default 'active',
  valid_from       timestamptz,
  valid_to         timestamptz,
  notes            text,
  created_at       timestamptz not null default now()
);

create table if not exists customer_auth (
  customer_id    bigint primary key references customers(id) on delete cascade,
  otp_code       text,
  otp_expires_at timestamptz,
  pin_hash       text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists platform_accounts (
  id                 bigint generated by default as identity primary key,
  platform_code      text        not null,
  account_email      text        not null,
  account_password   text,
  notes              text,
  owner_renewal_date date,
  renewal_cost       numeric(12,2) default 0,
  renewal_currency   text        default 'PEN',
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create table if not exists account_slots (
  id                  bigint generated by default as identity primary key,
  platform_account_id bigint      not null references platform_accounts(id) on delete cascade,
  customer_id         bigint      references customers(id) on delete set null,
  slot_number         int,
  slot_label          text,
  member_email        text        default '',
  email_type          text        default 'admin',    -- admin | customer | client
  member_password     text        default '',
  status              text        not null default 'free',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists subscriptions (
  id                     bigint generated by default as identity primary key,
  customer_id            bigint      references customers(id) on delete set null,
  platform_code          text,
  platform_account_id    bigint      references platform_accounts(id) on delete set null,
  account_slot_id        bigint      references account_slots(id) on delete set null,
  activation_email       text,
  activation_email_owner text,
  plan_price             numeric(12,2) default 0,
  currency               text        default 'PEN',
  start_date             date,
  renewal_date           date,
  subscription_status    text        not null default 'active',
  notes                  text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create table if not exists payments (
  id              bigint generated by default as identity primary key,
  customer_id     bigint      references customers(id) on delete set null,
  subscription_id bigint      references subscriptions(id) on delete set null,
  amount          numeric(12,2),
  currency        text        default 'PEN',
  payment_method  text,
  payment_status  text        not null default 'pending',
  coverage_from   date,
  coverage_to     date,
  proof_url       text,
  notes           text,
  verified_at     timestamptz,
  created_at      timestamptz not null default now()
);

create table if not exists events_log (
  id           bigint generated by default as identity primary key,
  entity_type  text        not null,
  entity_id    text,
  event_type   text        not null,
  old_value    jsonb,
  new_value    jsonb,
  performed_by text        default 'system',
  performed_at timestamptz not null default now(),
  reason       text
);

create table if not exists orders (
  id               bigint generated by default as identity primary key,
  order_id         text        not null,
  full_name        text,
  email            text,
  whatsapp         text,
  service          text,
  duration         text,
  price_pen        text,       -- histórico: texto tipo "S/. 6.00"; el monto real va en amount_pen (002)
  price_usd        text,
  payment_method   text,
  status           text        not null default 'pending',
  assigned_account text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- Inventario heredado. El inventario vivo son los account_slots; se conserva por los datos.
create table if not exists stock (
  id                text primary key,
  service           text,
  account_data      text,
  is_used           boolean     default false,
  assigned_to_order text,
  created_at        timestamptz not null default now()
);

-- Índices de operación diaria (búsquedas del panel y consultas del núcleo).
create index if not exists customer_contacts_customer_idx   on customer_contacts(customer_id);
create index if not exists customer_contacts_normalized_idx on customer_contacts(contact_type, normalized_value);
create index if not exists customers_code_idx               on customers(customer_code);
create index if not exists platform_accounts_code_email_idx on platform_accounts(platform_code, account_email);
create index if not exists account_slots_account_idx        on account_slots(platform_account_id, slot_number);
create index if not exists account_slots_customer_idx       on account_slots(customer_id);
create index if not exists subscriptions_customer_idx       on subscriptions(customer_id);
create index if not exists subscriptions_slot_idx           on subscriptions(account_slot_id);
create index if not exists subscriptions_status_renewal_idx on subscriptions(subscription_status, renewal_date);
create index if not exists payments_customer_idx            on payments(customer_id, created_at desc);
create index if not exists payments_status_idx              on payments(payment_status, created_at desc);
create index if not exists events_log_entity_idx            on events_log(entity_type, entity_id, id desc);

-- El volcado de Supabase trae Row Level Security activado con políticas atadas a
-- auth.uid(), que aquí no existe. Con RLS encendido y sin políticas, mpb_app (que
-- no es dueño de las tablas) vería cero filas. La autorización vive en la app.
do $$
declare
  t record;
begin
  for t in select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
            where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
  loop
    execute format('alter table public.%I disable row level security', t.relname);
  end loop;
end $$;
